weights: v5lite-g.pt
cfg: models/v5Lite-g.yaml
data: data.yaml
hyp:
  lr0: 0.00239
  lrf: 0.0664
  momentum: 0.92338
  weight_decay: 0.00067
  warmup_epochs: 2.48
  warmup_momentum: 0.58137
  warmup_bias_lr: 0.132
  box: 0.03625
  cls: 0.017833125
  cls_pw: 0.7253
  obj: 1.33073
  obj_pw: 0.76709
  iou_t: 0.2
  anchor_t: 2.24608
  anchors: 2.62693
  fl_gamma: 0.0
  hsv_h: 0.02123
  hsv_s: 0.89921
  hsv_v: 0.29502
  degrees: 0.0
  translate: 0.06881
  scale: 0.48727
  shear: 0.0
  perspective: 0.0
  flipud: 0.0
  fliplr: 0.5
  mosaic: 0.166
  mixup: 0.0
  label_smoothing: 0.0
epochs: 50
batch_size: 32
img_size:
- 640
- 640
rect: false
resume: false
nosave: true
notest: true
noautoanchor: false
evolve: true
bucket: ''
cache_images: false
image_weights: false
device: '0'
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
workers: 4
project: runs/train
entity: null
name: evolve
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
patience: 1000
world_size: 1
global_rank: -1
save_dir: runs\train\evolve
total_batch_size: 32
