weights: v5lite-s.pt
cfg: models/v5Lite-s.yaml
data: data.yaml
hyp:
  lr0: 0.00157
  lrf: 0.195
  momentum: 0.94962
  weight_decay: 0.00054
  warmup_epochs: 3.11
  warmup_momentum: 0.95
  warmup_bias_lr: 0.03171
  box: 0.0301
  cls: 0.05312125
  cls_pw: 0.8555
  obj: 1.57312
  obj_pw: 0.53186
  iou_t: 0.2
  anchor_t: 3.98197
  anchors: 2.0
  fl_gamma: 0.0
  hsv_h: 0.01321
  hsv_s: 0.856
  hsv_v: 0.547
  degrees: 0.0
  translate: 0.05523
  scale: 0.52929
  shear: 0.0
  perspective: 0.0
  flipud: 0.0
  fliplr: 0.5
  mosaic: 0.24986
  mixup: 0.0
  label_smoothing: 0.0
epochs: 10
batch_size: 32
img_size:
- 640
- 640
rect: false
resume: false
nosave: true
notest: true
noautoanchor: false
evolve: true
bucket: ''
cache_images: false
image_weights: false
device: '0'
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
workers: 8
project: runs/train
entity: null
name: evolve
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
patience: 100
world_size: 1
global_rank: -1
save_dir: runs\train\evolve
total_batch_size: 32
